spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: rnrdj123
    url: jdbc:mariadb://localhost:3306/dataJpa

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100


logging:
  level:
    org.hibernate.SQL: debug
    com.example.datajpa: debug
